//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension TimesheetSyncApi.AppleStoreBilling {

    /**
    Get Apple App Store subscription status

    Check the current status of the user's Apple App Store subscription including expiry time and renewal state.
    */
    public enum GetAppleStoreSubscriptionStatus {

        public static let service = APIService<Response>(id: "getAppleStoreSubscriptionStatus", tag: "Apple Store Billing", method: "GET", path: "/v1/billing/applestore/subscription/status", hasBody: false, securityRequirement: SecurityRequirement(type: "bearerAuth", scopes: []))

        public final class Request: APIRequest<Response> {

            public init() {
                super.init(service: GetAppleStoreSubscriptionStatus.service)
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = AppleSubscriptionStatusResponse

            /** Subscription status retrieved */
            case status200(AppleSubscriptionStatusResponse)

            /** User not authorized or not registered */
            case status401

            /** No Apple App Store subscription found for user */
            case status404

            public var success: AppleSubscriptionStatusResponse? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                default: return ()
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status401: return 401
                case .status404: return 404
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .status401: return false
                case .status404: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(AppleSubscriptionStatusResponse.self, from: data))
                case 401: self = .status401
                case 404: self = .status404
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
