//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AcknowledgeResponse: APIModel {

    public var acknowledged: Bool?

    public var acknowledgedAt: Int?

    public var active: Bool?

    public var details: String?

    public var errorCode: Int?

    public var expiryTimeMillis: Int?

    public var isActive: Bool?

    public var message: String?

    public var subscriptionId: String?

    public var userId: String?

    public init(acknowledged: Bool? = nil, acknowledgedAt: Int? = nil, active: Bool? = nil, details: String? = nil, errorCode: Int? = nil, expiryTimeMillis: Int? = nil, isActive: Bool? = nil, message: String? = nil, subscriptionId: String? = nil, userId: String? = nil) {
        self.acknowledged = acknowledged
        self.acknowledgedAt = acknowledgedAt
        self.active = active
        self.details = details
        self.errorCode = errorCode
        self.expiryTimeMillis = expiryTimeMillis
        self.isActive = isActive
        self.message = message
        self.subscriptionId = subscriptionId
        self.userId = userId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        acknowledged = try container.decodeIfPresent("acknowledged")
        acknowledgedAt = try container.decodeIfPresent("acknowledgedAt")
        active = try container.decodeIfPresent("active")
        details = try container.decodeIfPresent("details")
        errorCode = try container.decodeIfPresent("errorCode")
        expiryTimeMillis = try container.decodeIfPresent("expiryTimeMillis")
        isActive = try container.decodeIfPresent("isActive")
        message = try container.decodeIfPresent("message")
        subscriptionId = try container.decodeIfPresent("subscriptionId")
        userId = try container.decodeIfPresent("userId")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(acknowledged, forKey: "acknowledged")
        try container.encodeIfPresent(acknowledgedAt, forKey: "acknowledgedAt")
        try container.encodeIfPresent(active, forKey: "active")
        try container.encodeIfPresent(details, forKey: "details")
        try container.encodeIfPresent(errorCode, forKey: "errorCode")
        try container.encodeIfPresent(expiryTimeMillis, forKey: "expiryTimeMillis")
        try container.encodeIfPresent(isActive, forKey: "isActive")
        try container.encodeIfPresent(message, forKey: "message")
        try container.encodeIfPresent(subscriptionId, forKey: "subscriptionId")
        try container.encodeIfPresent(userId, forKey: "userId")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AcknowledgeResponse else { return false }
      guard self.acknowledged == object.acknowledged else { return false }
      guard self.acknowledgedAt == object.acknowledgedAt else { return false }
      guard self.active == object.active else { return false }
      guard self.details == object.details else { return false }
      guard self.errorCode == object.errorCode else { return false }
      guard self.expiryTimeMillis == object.expiryTimeMillis else { return false }
      guard self.isActive == object.isActive else { return false }
      guard self.message == object.message else { return false }
      guard self.subscriptionId == object.subscriptionId else { return false }
      guard self.userId == object.userId else { return false }
      return true
    }

    public static func == (lhs: AcknowledgeResponse, rhs: AcknowledgeResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
