//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AcknowledgeRequest: APIModel {

    public var packageName: String?

    public var purchaseToken: String?

    public var reason: String?

    public var sendNotification: Bool?

    public var subscriptionId: String?

    public var userId: String?

    public init(packageName: String? = nil, purchaseToken: String? = nil, reason: String? = nil, sendNotification: Bool? = nil, subscriptionId: String? = nil, userId: String? = nil) {
        self.packageName = packageName
        self.purchaseToken = purchaseToken
        self.reason = reason
        self.sendNotification = sendNotification
        self.subscriptionId = subscriptionId
        self.userId = userId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        packageName = try container.decodeIfPresent("packageName")
        purchaseToken = try container.decodeIfPresent("purchaseToken")
        reason = try container.decodeIfPresent("reason")
        sendNotification = try container.decodeIfPresent("sendNotification")
        subscriptionId = try container.decodeIfPresent("subscriptionId")
        userId = try container.decodeIfPresent("userId")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(packageName, forKey: "packageName")
        try container.encodeIfPresent(purchaseToken, forKey: "purchaseToken")
        try container.encodeIfPresent(reason, forKey: "reason")
        try container.encodeIfPresent(sendNotification, forKey: "sendNotification")
        try container.encodeIfPresent(subscriptionId, forKey: "subscriptionId")
        try container.encodeIfPresent(userId, forKey: "userId")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AcknowledgeRequest else { return false }
      guard self.packageName == object.packageName else { return false }
      guard self.purchaseToken == object.purchaseToken else { return false }
      guard self.reason == object.reason else { return false }
      guard self.sendNotification == object.sendNotification else { return false }
      guard self.subscriptionId == object.subscriptionId else { return false }
      guard self.userId == object.userId else { return false }
      return true
    }

    public static func == (lhs: AcknowledgeRequest, rhs: AcknowledgeRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
