//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AppleVerifyPurchaseRequest: APIModel {

    public var isTest: Bool?

    public var productId: String?

    public var test: Bool?

    public var transactionId: String?

    public var userId: String?

    public init(isTest: Bool? = nil, productId: String? = nil, test: Bool? = nil, transactionId: String? = nil, userId: String? = nil) {
        self.isTest = isTest
        self.productId = productId
        self.test = test
        self.transactionId = transactionId
        self.userId = userId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        isTest = try container.decodeIfPresent("isTest")
        productId = try container.decodeIfPresent("productId")
        test = try container.decodeIfPresent("test")
        transactionId = try container.decodeIfPresent("transactionId")
        userId = try container.decodeIfPresent("userId")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(isTest, forKey: "isTest")
        try container.encodeIfPresent(productId, forKey: "productId")
        try container.encodeIfPresent(test, forKey: "test")
        try container.encodeIfPresent(transactionId, forKey: "transactionId")
        try container.encodeIfPresent(userId, forKey: "userId")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AppleVerifyPurchaseRequest else { return false }
      guard self.isTest == object.isTest else { return false }
      guard self.productId == object.productId else { return false }
      guard self.test == object.test else { return false }
      guard self.transactionId == object.transactionId else { return false }
      guard self.userId == object.userId else { return false }
      return true
    }

    public static func == (lhs: AppleVerifyPurchaseRequest, rhs: AppleVerifyPurchaseRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
