//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AppleSubscriptionStatusResponse: APIModel {

    public var active: Bool?

    public var autoRenewStatus: Bool?

    public var expiresDate: Int?

    public var hasActiveSubscription: Bool?

    public var isActive: Bool?

    public var message: String?

    public var originalTransactionId: String?

    public var productId: String?

    public init(active: Bool? = nil, autoRenewStatus: Bool? = nil, expiresDate: Int? = nil, hasActiveSubscription: Bool? = nil, isActive: Bool? = nil, message: String? = nil, originalTransactionId: String? = nil, productId: String? = nil) {
        self.active = active
        self.autoRenewStatus = autoRenewStatus
        self.expiresDate = expiresDate
        self.hasActiveSubscription = hasActiveSubscription
        self.isActive = isActive
        self.message = message
        self.originalTransactionId = originalTransactionId
        self.productId = productId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        active = try container.decodeIfPresent("active")
        autoRenewStatus = try container.decodeIfPresent("autoRenewStatus")
        expiresDate = try container.decodeIfPresent("expiresDate")
        hasActiveSubscription = try container.decodeIfPresent("hasActiveSubscription")
        isActive = try container.decodeIfPresent("isActive")
        message = try container.decodeIfPresent("message")
        originalTransactionId = try container.decodeIfPresent("originalTransactionId")
        productId = try container.decodeIfPresent("productId")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(active, forKey: "active")
        try container.encodeIfPresent(autoRenewStatus, forKey: "autoRenewStatus")
        try container.encodeIfPresent(expiresDate, forKey: "expiresDate")
        try container.encodeIfPresent(hasActiveSubscription, forKey: "hasActiveSubscription")
        try container.encodeIfPresent(isActive, forKey: "isActive")
        try container.encodeIfPresent(message, forKey: "message")
        try container.encodeIfPresent(originalTransactionId, forKey: "originalTransactionId")
        try container.encodeIfPresent(productId, forKey: "productId")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AppleSubscriptionStatusResponse else { return false }
      guard self.active == object.active else { return false }
      guard self.autoRenewStatus == object.autoRenewStatus else { return false }
      guard self.expiresDate == object.expiresDate else { return false }
      guard self.hasActiveSubscription == object.hasActiveSubscription else { return false }
      guard self.isActive == object.isActive else { return false }
      guard self.message == object.message else { return false }
      guard self.originalTransactionId == object.originalTransactionId else { return false }
      guard self.productId == object.productId else { return false }
      return true
    }

    public static func == (lhs: AppleSubscriptionStatusResponse, rhs: AppleSubscriptionStatusResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
