//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AppleVerificationResponse: APIModel {

    public var message: String?

    public var originalTransactionId: String?

    public var productId: String?

    public var transactionId: String?

    public var valid: Bool?

    public init(message: String? = nil, originalTransactionId: String? = nil, productId: String? = nil, transactionId: String? = nil, valid: Bool? = nil) {
        self.message = message
        self.originalTransactionId = originalTransactionId
        self.productId = productId
        self.transactionId = transactionId
        self.valid = valid
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        message = try container.decodeIfPresent("message")
        originalTransactionId = try container.decodeIfPresent("originalTransactionId")
        productId = try container.decodeIfPresent("productId")
        transactionId = try container.decodeIfPresent("transactionId")
        valid = try container.decodeIfPresent("valid")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(message, forKey: "message")
        try container.encodeIfPresent(originalTransactionId, forKey: "originalTransactionId")
        try container.encodeIfPresent(productId, forKey: "productId")
        try container.encodeIfPresent(transactionId, forKey: "transactionId")
        try container.encodeIfPresent(valid, forKey: "valid")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AppleVerificationResponse else { return false }
      guard self.message == object.message else { return false }
      guard self.originalTransactionId == object.originalTransactionId else { return false }
      guard self.productId == object.productId else { return false }
      guard self.transactionId == object.transactionId else { return false }
      guard self.valid == object.valid else { return false }
      return true
    }

    public static func == (lhs: AppleVerificationResponse, rhs: AppleVerificationResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
