//
// DeviceDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeviceDto: Codable {

    public var _id: String?
    public var name: String?
    public var registrationId: String?
    public var user: String?
    public var deleted: Bool?
    public var lastUpdate: Int64?
    public var created: Int64?

    public init(_id: String?, name: String?, registrationId: String?, user: String?, deleted: Bool?, lastUpdate: Int64?, created: Int64?) {
        self._id = _id
        self.name = name
        self.registrationId = registrationId
        self.user = user
        self.deleted = deleted
        self.lastUpdate = lastUpdate
        self.created = created
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case registrationId
        case user
        case deleted
        case lastUpdate
        case created
    }

}

