//
// DeviceCreateDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeviceCreateDto: Codable {

    public var name: String?
    public var registrationId: String?

    public init(name: String?, registrationId: String?) {
        self.name = name
        self.registrationId = registrationId
    }


}

