//
// ExpenseSyncDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ExpenseSyncDto: Codable {

    public var _id: String?
    public var user: String?
    public var deleted: Bool?
    public var lastUpdate: Int64?
    public var created: Int64?
    public var taskId: String?
    public var _description: String?
    public var dateTime: String?
    public var amount: Double?
    public var refunded: Bool?

    public init(_id: String?, user: String?, deleted: Bool?, lastUpdate: Int64?, created: Int64?, taskId: String?, _description: String?, dateTime: String?, amount: Double?, refunded: Bool?) {
        self._id = _id
        self.user = user
        self.deleted = deleted
        self.lastUpdate = lastUpdate
        self.created = created
        self.taskId = taskId
        self._description = _description
        self.dateTime = dateTime
        self.amount = amount
        self.refunded = refunded
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case user
        case deleted
        case lastUpdate
        case created
        case taskId
        case _description = "description"
        case dateTime
        case amount
        case refunded
    }

}

