//
// PauseSyncDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PauseSyncDto: Codable {

    public var _id: String?
    public var user: String?
    public var deleted: Bool?
    public var running: Bool?
    public var lastUpdate: Int64?
    public var created: Int64?
    public var taskId: String?
    public var _description: String?
    public var startDateTime: String?
    public var endDateTime: String?

    public init(_id: String?, user: String?, deleted: Bool?, running: Bool?, lastUpdate: Int64?, created: Int64?, taskId: String?, _description: String?, startDateTime: String?, endDateTime: String?) {
        self._id = _id
        self.user = user
        self.deleted = deleted
        self.running = running
        self.lastUpdate = lastUpdate
        self.created = created
        self.taskId = taskId
        self._description = _description
        self.startDateTime = startDateTime
        self.endDateTime = endDateTime
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case user
        case deleted
        case running
        case lastUpdate
        case created
        case taskId
        case _description = "description"
        case startDateTime
        case endDateTime
    }

}

