//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class PauseSyncDto: APIModel {

    public var created: Int?

    public var deleted: Bool?

    public var description: String?

    public var endDateTime: String?

    public var id: String?

    public var lastUpdate: Int?

    public var running: Bool?

    public var startDateTime: String?

    public var taskId: String?

    public var user: String?

    public init(created: Int? = nil, deleted: Bool? = nil, description: String? = nil, endDateTime: String? = nil, id: String? = nil, lastUpdate: Int? = nil, running: Bool? = nil, startDateTime: String? = nil, taskId: String? = nil, user: String? = nil) {
        self.created = created
        self.deleted = deleted
        self.description = description
        self.endDateTime = endDateTime
        self.id = id
        self.lastUpdate = lastUpdate
        self.running = running
        self.startDateTime = startDateTime
        self.taskId = taskId
        self.user = user
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        created = try container.decodeIfPresent("created")
        deleted = try container.decodeIfPresent("deleted")
        description = try container.decodeIfPresent("description")
        endDateTime = try container.decodeIfPresent("endDateTime")
        id = try container.decodeIfPresent("id")
        lastUpdate = try container.decodeIfPresent("lastUpdate")
        running = try container.decodeIfPresent("running")
        startDateTime = try container.decodeIfPresent("startDateTime")
        taskId = try container.decodeIfPresent("taskId")
        user = try container.decodeIfPresent("user")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(created, forKey: "created")
        try container.encodeIfPresent(deleted, forKey: "deleted")
        try container.encodeIfPresent(description, forKey: "description")
        try container.encodeIfPresent(endDateTime, forKey: "endDateTime")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(lastUpdate, forKey: "lastUpdate")
        try container.encodeIfPresent(running, forKey: "running")
        try container.encodeIfPresent(startDateTime, forKey: "startDateTime")
        try container.encodeIfPresent(taskId, forKey: "taskId")
        try container.encodeIfPresent(user, forKey: "user")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? PauseSyncDto else { return false }
      guard self.created == object.created else { return false }
      guard self.deleted == object.deleted else { return false }
      guard self.description == object.description else { return false }
      guard self.endDateTime == object.endDateTime else { return false }
      guard self.id == object.id else { return false }
      guard self.lastUpdate == object.lastUpdate else { return false }
      guard self.running == object.running else { return false }
      guard self.startDateTime == object.startDateTime else { return false }
      guard self.taskId == object.taskId else { return false }
      guard self.user == object.user else { return false }
      return true
    }

    public static func == (lhs: PauseSyncDto, rhs: PauseSyncDto) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
