//
// ProjectSyncDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProjectSyncDto: Codable {

    public var _id: String?
    public var user: String?
    public var deleted: Bool?
    public var lastUpdate: Int64?
    public var created: Int64?
    public var teamId: String?
    public var title: String?
    public var _description: String?
    public var employer: String?
    public var office: String?
    public var color: Int?
    public var taskDefaultBillable: Bool?
    public var taskDefaultRateId: String?
    public var archived: Bool?
    public var salary: Double?

    public init(_id: String?, user: String?, deleted: Bool?, lastUpdate: Int64?, created: Int64?, teamId: String?, title: String?, _description: String?, employer: String?, office: String?, color: Int?, taskDefaultBillable: Bool?, taskDefaultRateId: String?, archived: Bool?, salary: Double?) {
        self._id = _id
        self.user = user
        self.deleted = deleted
        self.lastUpdate = lastUpdate
        self.created = created
        self.teamId = teamId
        self.title = title
        self._description = _description
        self.employer = employer
        self.office = office
        self.color = color
        self.taskDefaultBillable = taskDefaultBillable
        self.taskDefaultRateId = taskDefaultRateId
        self.archived = archived
        self.salary = salary
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case user
        case deleted
        case lastUpdate
        case created
        case teamId
        case title
        case _description = "description"
        case employer
        case office
        case color
        case taskDefaultBillable
        case taskDefaultRateId
        case archived
        case salary
    }

}

