//
// PublicProfileDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PublicProfileDto: Codable {

    public var expires: Int64?
    public var permission: Int?
    public var status: Int?
    public var plan: Int?
    public var members: Int?
    public var email: String?
    public var paymentOption: String?
    public var imageUrl: String?
    public var business: String?
    public var taxId: String?
    public var firstname: String?
    public var lastname: String?
    public var street: String?
    public var city: String?
    public var state: String?
    public var zip: String?
    public var country: String?
    public var countryName: String?
    public var language: String?
    public var referrer: String?
    public var includeTaxForBusiness: Bool?
    public var newsletter: Bool?
    public var gdprConsent: Bool?
    public var invited: Bool?
    public var activatedTeams: Bool?
    public var activated: Bool?
    public var cancellationOffer: Bool?
    public var user: String?
    public var lastUpdate: Int64?
    public var subscriptionActive: Bool?
    public var subscriptionCancelled: Bool?
    public var subscriptionInactive: Bool?
    public var createdAt: Date?
    public var startedTestimonial: Date?
    public var activationDate: Date?
    public var cancellationDate: Date?
    public var active: Bool?
    public var displayName: String?
    public var currency: String?
    public var valid: Bool?
    public var expired: Bool?
    public var member: Bool?
    public var pending: Bool?
    public var eu: Bool?
    public var at: Bool?
    public var product: String?
    public var pro: Bool?
    public var plus: Bool?
    public var monthly: Bool?
    public var yearly: Bool?
    public var inactive: Bool?
    public var validProfile: Bool?
    public var validAndActivated: Bool?
    public var admin: Bool?
    public var payPalPayment: Bool?
    public var stripePayment: Bool?
    public var invoicePayment: Bool?
    public var businessCustomer: Bool?
    public var euCustomer: Bool?
    public var trial: Bool?
    public var licenseHolder: Bool?
    public var licenseQuantity: Int?
    public var initials: String?

    public init(expires: Int64?, permission: Int?, status: Int?, plan: Int?, members: Int?, email: String?, paymentOption: String?, imageUrl: String?, business: String?, taxId: String?, firstname: String?, lastname: String?, street: String?, city: String?, state: String?, zip: String?, country: String?, countryName: String?, language: String?, referrer: String?, includeTaxForBusiness: Bool?, newsletter: Bool?, gdprConsent: Bool?, invited: Bool?, activatedTeams: Bool?, activated: Bool?, cancellationOffer: Bool?, user: String?, lastUpdate: Int64?, subscriptionActive: Bool?, subscriptionCancelled: Bool?, subscriptionInactive: Bool?, createdAt: Date?, startedTestimonial: Date?, activationDate: Date?, cancellationDate: Date?, active: Bool?, displayName: String?, currency: String?, valid: Bool?, expired: Bool?, member: Bool?, pending: Bool?, eu: Bool?, at: Bool?, product: String?, pro: Bool?, plus: Bool?, monthly: Bool?, yearly: Bool?, inactive: Bool?, validProfile: Bool?, validAndActivated: Bool?, admin: Bool?, payPalPayment: Bool?, stripePayment: Bool?, invoicePayment: Bool?, businessCustomer: Bool?, euCustomer: Bool?, trial: Bool?, licenseHolder: Bool?, licenseQuantity: Int?, initials: String?) {
        self.expires = expires
        self.permission = permission
        self.status = status
        self.plan = plan
        self.members = members
        self.email = email
        self.paymentOption = paymentOption
        self.imageUrl = imageUrl
        self.business = business
        self.taxId = taxId
        self.firstname = firstname
        self.lastname = lastname
        self.street = street
        self.city = city
        self.state = state
        self.zip = zip
        self.country = country
        self.countryName = countryName
        self.language = language
        self.referrer = referrer
        self.includeTaxForBusiness = includeTaxForBusiness
        self.newsletter = newsletter
        self.gdprConsent = gdprConsent
        self.invited = invited
        self.activatedTeams = activatedTeams
        self.activated = activated
        self.cancellationOffer = cancellationOffer
        self.user = user
        self.lastUpdate = lastUpdate
        self.subscriptionActive = subscriptionActive
        self.subscriptionCancelled = subscriptionCancelled
        self.subscriptionInactive = subscriptionInactive
        self.createdAt = createdAt
        self.startedTestimonial = startedTestimonial
        self.activationDate = activationDate
        self.cancellationDate = cancellationDate
        self.active = active
        self.displayName = displayName
        self.currency = currency
        self.valid = valid
        self.expired = expired
        self.member = member
        self.pending = pending
        self.eu = eu
        self.at = at
        self.product = product
        self.pro = pro
        self.plus = plus
        self.monthly = monthly
        self.yearly = yearly
        self.inactive = inactive
        self.validProfile = validProfile
        self.validAndActivated = validAndActivated
        self.admin = admin
        self.payPalPayment = payPalPayment
        self.stripePayment = stripePayment
        self.invoicePayment = invoicePayment
        self.businessCustomer = businessCustomer
        self.euCustomer = euCustomer
        self.trial = trial
        self.licenseHolder = licenseHolder
        self.licenseQuantity = licenseQuantity
        self.initials = initials
    }


}

