//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class RateSyncDto: APIModel {

    public var archived: Bool?

    public var created: Int?

    public var deleted: Bool?

    public var enabled: Bool?

    public var extra: Double?

    public var factor: Double?

    public var id: String?

    public var lastUpdate: Int?

    public var teamId: String?

    public var title: String?

    public var user: String?

    public init(archived: Bool? = nil, created: Int? = nil, deleted: Bool? = nil, enabled: Bool? = nil, extra: Double? = nil, factor: Double? = nil, id: String? = nil, lastUpdate: Int? = nil, teamId: String? = nil, title: String? = nil, user: String? = nil) {
        self.archived = archived
        self.created = created
        self.deleted = deleted
        self.enabled = enabled
        self.extra = extra
        self.factor = factor
        self.id = id
        self.lastUpdate = lastUpdate
        self.teamId = teamId
        self.title = title
        self.user = user
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        archived = try container.decodeIfPresent("archived")
        created = try container.decodeIfPresent("created")
        deleted = try container.decodeIfPresent("deleted")
        enabled = try container.decodeIfPresent("enabled")
        extra = try container.decodeIfPresent("extra")
        factor = try container.decodeIfPresent("factor")
        id = try container.decodeIfPresent("id")
        lastUpdate = try container.decodeIfPresent("lastUpdate")
        teamId = try container.decodeIfPresent("teamId")
        title = try container.decodeIfPresent("title")
        user = try container.decodeIfPresent("user")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(archived, forKey: "archived")
        try container.encodeIfPresent(created, forKey: "created")
        try container.encodeIfPresent(deleted, forKey: "deleted")
        try container.encodeIfPresent(enabled, forKey: "enabled")
        try container.encodeIfPresent(extra, forKey: "extra")
        try container.encodeIfPresent(factor, forKey: "factor")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(lastUpdate, forKey: "lastUpdate")
        try container.encodeIfPresent(teamId, forKey: "teamId")
        try container.encodeIfPresent(title, forKey: "title")
        try container.encodeIfPresent(user, forKey: "user")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? RateSyncDto else { return false }
      guard self.archived == object.archived else { return false }
      guard self.created == object.created else { return false }
      guard self.deleted == object.deleted else { return false }
      guard self.enabled == object.enabled else { return false }
      guard self.extra == object.extra else { return false }
      guard self.factor == object.factor else { return false }
      guard self.id == object.id else { return false }
      guard self.lastUpdate == object.lastUpdate else { return false }
      guard self.teamId == object.teamId else { return false }
      guard self.title == object.title else { return false }
      guard self.user == object.user else { return false }
      return true
    }

    public static func == (lhs: RateSyncDto, rhs: RateSyncDto) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
