//
// RateSyncDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RateSyncDto: Codable {

    public var _id: String?
    public var title: String?
    public var factor: Double?
    public var extra: Double?
    public var enabled: Bool?
    public var teamId: String?
    public var user: String?
    public var deleted: Bool?
    public var lastUpdate: Int64?
    public var created: Int64?

    public init(_id: String?, title: String?, factor: Double?, extra: Double?, enabled: Bool?, teamId: String?, user: String?, deleted: Bool?, lastUpdate: Int64?, created: Int64?) {
        self._id = _id
        self.title = title
        self.factor = factor
        self.extra = extra
        self.enabled = enabled
        self.teamId = teamId
        self.user = user
        self.deleted = deleted
        self.lastUpdate = lastUpdate
        self.created = created
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case factor
        case extra
        case enabled
        case teamId
        case user
        case deleted
        case lastUpdate
        case created
    }

}

