//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class SettingsDto: APIModel {

    public var autofillProjectSelection: Bool?

    public var csvSeparator: String?

    public var currency: String?

    public var dateFormat: String?

    public var defaultBreakDuration: Int?

    public var defaultTaskDuration: Int?

    public var distance: String?

    public var durationFormat: String?

    public var entriesPerPage: Int?

    public var firstDay: Int?

    public var language: String?

    public var lastUpdate: Int?

    public var monthlySummary: Bool?

    public var pauseEditView: Bool?

    public var pauseRounding: Int?

    public var pauseRoundingType: Int?

    public var showRelatives: Bool?

    public var slotDuration: Int?

    public var snapDuration: Int?

    public var theme: String?

    public var timeFormat: String?

    public var timerEditView: Bool?

    public var timerRounding: Int?

    public var timerRoundingType: Int?

    public var timezone: String?

    public var weeklySummary: Bool?

    public init(autofillProjectSelection: Bool? = nil, csvSeparator: String? = nil, currency: String? = nil, dateFormat: String? = nil, defaultBreakDuration: Int? = nil, defaultTaskDuration: Int? = nil, distance: String? = nil, durationFormat: String? = nil, entriesPerPage: Int? = nil, firstDay: Int? = nil, language: String? = nil, lastUpdate: Int? = nil, monthlySummary: Bool? = nil, pauseEditView: Bool? = nil, pauseRounding: Int? = nil, pauseRoundingType: Int? = nil, showRelatives: Bool? = nil, slotDuration: Int? = nil, snapDuration: Int? = nil, theme: String? = nil, timeFormat: String? = nil, timerEditView: Bool? = nil, timerRounding: Int? = nil, timerRoundingType: Int? = nil, timezone: String? = nil, weeklySummary: Bool? = nil) {
        self.autofillProjectSelection = autofillProjectSelection
        self.csvSeparator = csvSeparator
        self.currency = currency
        self.dateFormat = dateFormat
        self.defaultBreakDuration = defaultBreakDuration
        self.defaultTaskDuration = defaultTaskDuration
        self.distance = distance
        self.durationFormat = durationFormat
        self.entriesPerPage = entriesPerPage
        self.firstDay = firstDay
        self.language = language
        self.lastUpdate = lastUpdate
        self.monthlySummary = monthlySummary
        self.pauseEditView = pauseEditView
        self.pauseRounding = pauseRounding
        self.pauseRoundingType = pauseRoundingType
        self.showRelatives = showRelatives
        self.slotDuration = slotDuration
        self.snapDuration = snapDuration
        self.theme = theme
        self.timeFormat = timeFormat
        self.timerEditView = timerEditView
        self.timerRounding = timerRounding
        self.timerRoundingType = timerRoundingType
        self.timezone = timezone
        self.weeklySummary = weeklySummary
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        autofillProjectSelection = try container.decodeIfPresent("autofillProjectSelection")
        csvSeparator = try container.decodeIfPresent("csvSeparator")
        currency = try container.decodeIfPresent("currency")
        dateFormat = try container.decodeIfPresent("dateFormat")
        defaultBreakDuration = try container.decodeIfPresent("defaultBreakDuration")
        defaultTaskDuration = try container.decodeIfPresent("defaultTaskDuration")
        distance = try container.decodeIfPresent("distance")
        durationFormat = try container.decodeIfPresent("durationFormat")
        entriesPerPage = try container.decodeIfPresent("entriesPerPage")
        firstDay = try container.decodeIfPresent("firstDay")
        language = try container.decodeIfPresent("language")
        lastUpdate = try container.decodeIfPresent("lastUpdate")
        monthlySummary = try container.decodeIfPresent("monthlySummary")
        pauseEditView = try container.decodeIfPresent("pauseEditView")
        pauseRounding = try container.decodeIfPresent("pauseRounding")
        pauseRoundingType = try container.decodeIfPresent("pauseRoundingType")
        showRelatives = try container.decodeIfPresent("showRelatives")
        slotDuration = try container.decodeIfPresent("slotDuration")
        snapDuration = try container.decodeIfPresent("snapDuration")
        theme = try container.decodeIfPresent("theme")
        timeFormat = try container.decodeIfPresent("timeFormat")
        timerEditView = try container.decodeIfPresent("timerEditView")
        timerRounding = try container.decodeIfPresent("timerRounding")
        timerRoundingType = try container.decodeIfPresent("timerRoundingType")
        timezone = try container.decodeIfPresent("timezone")
        weeklySummary = try container.decodeIfPresent("weeklySummary")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(autofillProjectSelection, forKey: "autofillProjectSelection")
        try container.encodeIfPresent(csvSeparator, forKey: "csvSeparator")
        try container.encodeIfPresent(currency, forKey: "currency")
        try container.encodeIfPresent(dateFormat, forKey: "dateFormat")
        try container.encodeIfPresent(defaultBreakDuration, forKey: "defaultBreakDuration")
        try container.encodeIfPresent(defaultTaskDuration, forKey: "defaultTaskDuration")
        try container.encodeIfPresent(distance, forKey: "distance")
        try container.encodeIfPresent(durationFormat, forKey: "durationFormat")
        try container.encodeIfPresent(entriesPerPage, forKey: "entriesPerPage")
        try container.encodeIfPresent(firstDay, forKey: "firstDay")
        try container.encodeIfPresent(language, forKey: "language")
        try container.encodeIfPresent(lastUpdate, forKey: "lastUpdate")
        try container.encodeIfPresent(monthlySummary, forKey: "monthlySummary")
        try container.encodeIfPresent(pauseEditView, forKey: "pauseEditView")
        try container.encodeIfPresent(pauseRounding, forKey: "pauseRounding")
        try container.encodeIfPresent(pauseRoundingType, forKey: "pauseRoundingType")
        try container.encodeIfPresent(showRelatives, forKey: "showRelatives")
        try container.encodeIfPresent(slotDuration, forKey: "slotDuration")
        try container.encodeIfPresent(snapDuration, forKey: "snapDuration")
        try container.encodeIfPresent(theme, forKey: "theme")
        try container.encodeIfPresent(timeFormat, forKey: "timeFormat")
        try container.encodeIfPresent(timerEditView, forKey: "timerEditView")
        try container.encodeIfPresent(timerRounding, forKey: "timerRounding")
        try container.encodeIfPresent(timerRoundingType, forKey: "timerRoundingType")
        try container.encodeIfPresent(timezone, forKey: "timezone")
        try container.encodeIfPresent(weeklySummary, forKey: "weeklySummary")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? SettingsDto else { return false }
      guard self.autofillProjectSelection == object.autofillProjectSelection else { return false }
      guard self.csvSeparator == object.csvSeparator else { return false }
      guard self.currency == object.currency else { return false }
      guard self.dateFormat == object.dateFormat else { return false }
      guard self.defaultBreakDuration == object.defaultBreakDuration else { return false }
      guard self.defaultTaskDuration == object.defaultTaskDuration else { return false }
      guard self.distance == object.distance else { return false }
      guard self.durationFormat == object.durationFormat else { return false }
      guard self.entriesPerPage == object.entriesPerPage else { return false }
      guard self.firstDay == object.firstDay else { return false }
      guard self.language == object.language else { return false }
      guard self.lastUpdate == object.lastUpdate else { return false }
      guard self.monthlySummary == object.monthlySummary else { return false }
      guard self.pauseEditView == object.pauseEditView else { return false }
      guard self.pauseRounding == object.pauseRounding else { return false }
      guard self.pauseRoundingType == object.pauseRoundingType else { return false }
      guard self.showRelatives == object.showRelatives else { return false }
      guard self.slotDuration == object.slotDuration else { return false }
      guard self.snapDuration == object.snapDuration else { return false }
      guard self.theme == object.theme else { return false }
      guard self.timeFormat == object.timeFormat else { return false }
      guard self.timerEditView == object.timerEditView else { return false }
      guard self.timerRounding == object.timerRounding else { return false }
      guard self.timerRoundingType == object.timerRoundingType else { return false }
      guard self.timezone == object.timezone else { return false }
      guard self.weeklySummary == object.weeklySummary else { return false }
      return true
    }

    public static func == (lhs: SettingsDto, rhs: SettingsDto) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
