//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class SubscriptionStatusResponse: APIModel {

    public var active: Bool?

    public var autoRenewing: Bool?

    public var cancellationReason: String?

    public var countryCode: String?

    public var details: String?

    public var errorCode: Int?

    public var expiryTimeMillis: Int?

    public var gracePeriodEndTimeMillis: Int?

    public var inGracePeriod: Bool?

    public var inTrial: Bool?

    public var isActive: Bool?

    public var lastRenewalTimeMillis: Int?

    public var message: String?

    public var paymentState: Int?

    public var priceAmountMicros: Int?

    public var priceCurrencyCode: String?

    public var productId: String?

    public var startTimeMillis: Int?

    public var status: Int?

    public var subscriptionId: String?

    public var success: Bool?

    public var userCancellationTimeMillis: Int?

    public var userId: String?

    public init(active: Bool? = nil, autoRenewing: Bool? = nil, cancellationReason: String? = nil, countryCode: String? = nil, details: String? = nil, errorCode: Int? = nil, expiryTimeMillis: Int? = nil, gracePeriodEndTimeMillis: Int? = nil, inGracePeriod: Bool? = nil, inTrial: Bool? = nil, isActive: Bool? = nil, lastRenewalTimeMillis: Int? = nil, message: String? = nil, paymentState: Int? = nil, priceAmountMicros: Int? = nil, priceCurrencyCode: String? = nil, productId: String? = nil, startTimeMillis: Int? = nil, status: Int? = nil, subscriptionId: String? = nil, success: Bool? = nil, userCancellationTimeMillis: Int? = nil, userId: String? = nil) {
        self.active = active
        self.autoRenewing = autoRenewing
        self.cancellationReason = cancellationReason
        self.countryCode = countryCode
        self.details = details
        self.errorCode = errorCode
        self.expiryTimeMillis = expiryTimeMillis
        self.gracePeriodEndTimeMillis = gracePeriodEndTimeMillis
        self.inGracePeriod = inGracePeriod
        self.inTrial = inTrial
        self.isActive = isActive
        self.lastRenewalTimeMillis = lastRenewalTimeMillis
        self.message = message
        self.paymentState = paymentState
        self.priceAmountMicros = priceAmountMicros
        self.priceCurrencyCode = priceCurrencyCode
        self.productId = productId
        self.startTimeMillis = startTimeMillis
        self.status = status
        self.subscriptionId = subscriptionId
        self.success = success
        self.userCancellationTimeMillis = userCancellationTimeMillis
        self.userId = userId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        active = try container.decodeIfPresent("active")
        autoRenewing = try container.decodeIfPresent("autoRenewing")
        cancellationReason = try container.decodeIfPresent("cancellationReason")
        countryCode = try container.decodeIfPresent("countryCode")
        details = try container.decodeIfPresent("details")
        errorCode = try container.decodeIfPresent("errorCode")
        expiryTimeMillis = try container.decodeIfPresent("expiryTimeMillis")
        gracePeriodEndTimeMillis = try container.decodeIfPresent("gracePeriodEndTimeMillis")
        inGracePeriod = try container.decodeIfPresent("inGracePeriod")
        inTrial = try container.decodeIfPresent("inTrial")
        isActive = try container.decodeIfPresent("isActive")
        lastRenewalTimeMillis = try container.decodeIfPresent("lastRenewalTimeMillis")
        message = try container.decodeIfPresent("message")
        paymentState = try container.decodeIfPresent("paymentState")
        priceAmountMicros = try container.decodeIfPresent("priceAmountMicros")
        priceCurrencyCode = try container.decodeIfPresent("priceCurrencyCode")
        productId = try container.decodeIfPresent("productId")
        startTimeMillis = try container.decodeIfPresent("startTimeMillis")
        status = try container.decodeIfPresent("status")
        subscriptionId = try container.decodeIfPresent("subscriptionId")
        success = try container.decodeIfPresent("success")
        userCancellationTimeMillis = try container.decodeIfPresent("userCancellationTimeMillis")
        userId = try container.decodeIfPresent("userId")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(active, forKey: "active")
        try container.encodeIfPresent(autoRenewing, forKey: "autoRenewing")
        try container.encodeIfPresent(cancellationReason, forKey: "cancellationReason")
        try container.encodeIfPresent(countryCode, forKey: "countryCode")
        try container.encodeIfPresent(details, forKey: "details")
        try container.encodeIfPresent(errorCode, forKey: "errorCode")
        try container.encodeIfPresent(expiryTimeMillis, forKey: "expiryTimeMillis")
        try container.encodeIfPresent(gracePeriodEndTimeMillis, forKey: "gracePeriodEndTimeMillis")
        try container.encodeIfPresent(inGracePeriod, forKey: "inGracePeriod")
        try container.encodeIfPresent(inTrial, forKey: "inTrial")
        try container.encodeIfPresent(isActive, forKey: "isActive")
        try container.encodeIfPresent(lastRenewalTimeMillis, forKey: "lastRenewalTimeMillis")
        try container.encodeIfPresent(message, forKey: "message")
        try container.encodeIfPresent(paymentState, forKey: "paymentState")
        try container.encodeIfPresent(priceAmountMicros, forKey: "priceAmountMicros")
        try container.encodeIfPresent(priceCurrencyCode, forKey: "priceCurrencyCode")
        try container.encodeIfPresent(productId, forKey: "productId")
        try container.encodeIfPresent(startTimeMillis, forKey: "startTimeMillis")
        try container.encodeIfPresent(status, forKey: "status")
        try container.encodeIfPresent(subscriptionId, forKey: "subscriptionId")
        try container.encodeIfPresent(success, forKey: "success")
        try container.encodeIfPresent(userCancellationTimeMillis, forKey: "userCancellationTimeMillis")
        try container.encodeIfPresent(userId, forKey: "userId")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? SubscriptionStatusResponse else { return false }
      guard self.active == object.active else { return false }
      guard self.autoRenewing == object.autoRenewing else { return false }
      guard self.cancellationReason == object.cancellationReason else { return false }
      guard self.countryCode == object.countryCode else { return false }
      guard self.details == object.details else { return false }
      guard self.errorCode == object.errorCode else { return false }
      guard self.expiryTimeMillis == object.expiryTimeMillis else { return false }
      guard self.gracePeriodEndTimeMillis == object.gracePeriodEndTimeMillis else { return false }
      guard self.inGracePeriod == object.inGracePeriod else { return false }
      guard self.inTrial == object.inTrial else { return false }
      guard self.isActive == object.isActive else { return false }
      guard self.lastRenewalTimeMillis == object.lastRenewalTimeMillis else { return false }
      guard self.message == object.message else { return false }
      guard self.paymentState == object.paymentState else { return false }
      guard self.priceAmountMicros == object.priceAmountMicros else { return false }
      guard self.priceCurrencyCode == object.priceCurrencyCode else { return false }
      guard self.productId == object.productId else { return false }
      guard self.startTimeMillis == object.startTimeMillis else { return false }
      guard self.status == object.status else { return false }
      guard self.subscriptionId == object.subscriptionId else { return false }
      guard self.success == object.success else { return false }
      guard self.userCancellationTimeMillis == object.userCancellationTimeMillis else { return false }
      guard self.userId == object.userId else { return false }
      return true
    }

    public static func == (lhs: SubscriptionStatusResponse, rhs: SubscriptionStatusResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
