//
// SyncData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SyncData: Codable {

    public var syncState: Int64?
    public var deviceId: String?
    public var projectState: Int64?
    public var todoState: Int64?
    public var taskState: Int64?
    public var pauseState: Int64?
    public var expenseState: Int64?
    public var noteState: Int64?
    public var tagState: Int64?
    public var taskTagState: Int64?
    public var rateState: Int64?
    public var teamState: Int64?
    public var teamMemberState: Int64?
    public var projectMemberState: Int64?
    public var projectCount: Int?
    public var todoCount: Int?
    public var taskCount: Int?
    public var pauseCount: Int?
    public var expenseCount: Int?
    public var noteCount: Int?
    public var tagCount: Int?
    public var taskTagCount: Int?
    public var rateCount: Int?
    public var teamCount: Int?
    public var teamMemberCount: Int?
    public var projectMemberCount: Int?
    public var projects: [ProjectSyncDto]?
    public var todos: [ToDoSyncDto]?
    public var tasks: [TaskSyncDto]?
    public var pauses: [PauseSyncDto]?
    public var expenses: [ExpenseSyncDto]?
    public var notes: [NoteSyncDto]?
    public var tags: [TagSyncDto]?
    public var taskTags: [TaskTagSyncDto]?
    public var rates: [RateSyncDto]?
    public var teams: [TeamSyncDto]?
    public var teamMembers: [TeamMemberSyncDto]?
    public var projectMembers: [ProjectMemberSyncDto]?

    public init(syncState: Int64?, deviceId: String?, projectState: Int64?, todoState: Int64?, taskState: Int64?, pauseState: Int64?, expenseState: Int64?, noteState: Int64?, tagState: Int64?, taskTagState: Int64?, rateState: Int64?, teamState: Int64?, teamMemberState: Int64?, projectMemberState: Int64?, projectCount: Int?, todoCount: Int?, taskCount: Int?, pauseCount: Int?, expenseCount: Int?, noteCount: Int?, tagCount: Int?, taskTagCount: Int?, rateCount: Int?, teamCount: Int?, teamMemberCount: Int?, projectMemberCount: Int?, projects: [ProjectSyncDto]?, todos: [ToDoSyncDto]?, tasks: [TaskSyncDto]?, pauses: [PauseSyncDto]?, expenses: [ExpenseSyncDto]?, notes: [NoteSyncDto]?, tags: [TagSyncDto]?, taskTags: [TaskTagSyncDto]?, rates: [RateSyncDto]?, teams: [TeamSyncDto]?, teamMembers: [TeamMemberSyncDto]?, projectMembers: [ProjectMemberSyncDto]?) {
        self.syncState = syncState
        self.deviceId = deviceId
        self.projectState = projectState
        self.todoState = todoState
        self.taskState = taskState
        self.pauseState = pauseState
        self.expenseState = expenseState
        self.noteState = noteState
        self.tagState = tagState
        self.taskTagState = taskTagState
        self.rateState = rateState
        self.teamState = teamState
        self.teamMemberState = teamMemberState
        self.projectMemberState = projectMemberState
        self.projectCount = projectCount
        self.todoCount = todoCount
        self.taskCount = taskCount
        self.pauseCount = pauseCount
        self.expenseCount = expenseCount
        self.noteCount = noteCount
        self.tagCount = tagCount
        self.taskTagCount = taskTagCount
        self.rateCount = rateCount
        self.teamCount = teamCount
        self.teamMemberCount = teamMemberCount
        self.projectMemberCount = projectMemberCount
        self.projects = projects
        self.todos = todos
        self.tasks = tasks
        self.pauses = pauses
        self.expenses = expenses
        self.notes = notes
        self.tags = tags
        self.taskTags = taskTags
        self.rates = rates
        self.teams = teams
        self.teamMembers = teamMembers
        self.projectMembers = projectMembers
    }


}

