//
// TaskTagSyncDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TaskTagSyncDto: Codable {

    public var _id: String?
    public var user: String?
    public var deleted: Bool?
    public var lastUpdate: Int64?
    public var created: Int64?
    public var taskId: String?
    public var tagId: String?

    public init(_id: String?, user: String?, deleted: Bool?, lastUpdate: Int64?, created: Int64?, taskId: String?, tagId: String?) {
        self._id = _id
        self.user = user
        self.deleted = deleted
        self.lastUpdate = lastUpdate
        self.created = created
        self.taskId = taskId
        self.tagId = tagId
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case user
        case deleted
        case lastUpdate
        case created
        case taskId
        case tagId
    }

}

