//
// TaskSyncDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TaskSyncDto: Codable {

    public var _id: String?
    public var user: String?
    public var deleted: Bool?
    public var running: Bool?
    public var lastUpdate: Int64?
    public var created: Int64?
    public var projectId: String?
    public var todoId: String?
    public var _description: String?
    public var location: String?
    public var locationEnd: String?
    public var startDateTime: String?
    public var endDateTime: String?
    public var feeling: Int?
    public var typeId: Int?
    public var paid: Bool?
    public var billed: Bool?
    public var billable: Bool?
    public var phoneNumber: String?
    public var distance: Double?
    public var rateId: String?
    public var signature: String?

    public init(_id: String?, user: String?, deleted: Bool?, running: Bool?, lastUpdate: Int64?, created: Int64?, projectId: String?, todoId: String?, _description: String?, location: String?, locationEnd: String?, startDateTime: String?, endDateTime: String?, feeling: Int?, typeId: Int?, paid: Bool?, billed: Bool?, billable: Bool?, phoneNumber: String?, distance: Double?, rateId: String?, signature: String?) {
        self._id = _id
        self.user = user
        self.deleted = deleted
        self.running = running
        self.lastUpdate = lastUpdate
        self.created = created
        self.projectId = projectId
        self.todoId = todoId
        self._description = _description
        self.location = location
        self.locationEnd = locationEnd
        self.startDateTime = startDateTime
        self.endDateTime = endDateTime
        self.feeling = feeling
        self.typeId = typeId
        self.paid = paid
        self.billed = billed
        self.billable = billable
        self.phoneNumber = phoneNumber
        self.distance = distance
        self.rateId = rateId
        self.signature = signature
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case user
        case deleted
        case running
        case lastUpdate
        case created
        case projectId
        case todoId
        case _description = "description"
        case location
        case locationEnd
        case startDateTime
        case endDateTime
        case feeling
        case typeId
        case paid
        case billed
        case billable
        case phoneNumber
        case distance
        case rateId
        case signature
    }

}

