//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class TeamSyncDto: APIModel {

    public var color: Int?

    public var created: Int?

    public var deleted: Bool?

    public var description: String?

    public var id: String?

    public var image: String?

    public var lastUpdate: Int?

    public var name: String?

    public var user: String?

    public init(color: Int? = nil, created: Int? = nil, deleted: Bool? = nil, description: String? = nil, id: String? = nil, image: String? = nil, lastUpdate: Int? = nil, name: String? = nil, user: String? = nil) {
        self.color = color
        self.created = created
        self.deleted = deleted
        self.description = description
        self.id = id
        self.image = image
        self.lastUpdate = lastUpdate
        self.name = name
        self.user = user
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        color = try container.decodeIfPresent("color")
        created = try container.decodeIfPresent("created")
        deleted = try container.decodeIfPresent("deleted")
        description = try container.decodeIfPresent("description")
        id = try container.decodeIfPresent("id")
        image = try container.decodeIfPresent("image")
        lastUpdate = try container.decodeIfPresent("lastUpdate")
        name = try container.decodeIfPresent("name")
        user = try container.decodeIfPresent("user")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(color, forKey: "color")
        try container.encodeIfPresent(created, forKey: "created")
        try container.encodeIfPresent(deleted, forKey: "deleted")
        try container.encodeIfPresent(description, forKey: "description")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(image, forKey: "image")
        try container.encodeIfPresent(lastUpdate, forKey: "lastUpdate")
        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(user, forKey: "user")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? TeamSyncDto else { return false }
      guard self.color == object.color else { return false }
      guard self.created == object.created else { return false }
      guard self.deleted == object.deleted else { return false }
      guard self.description == object.description else { return false }
      guard self.id == object.id else { return false }
      guard self.image == object.image else { return false }
      guard self.lastUpdate == object.lastUpdate else { return false }
      guard self.name == object.name else { return false }
      guard self.user == object.user else { return false }
      return true
    }

    public static func == (lhs: TeamSyncDto, rhs: TeamSyncDto) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
