//
// TeamSyncDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TeamSyncDto: Codable {

    public var _id: String?
    public var name: String?
    public var _description: String?
    public var image: String?
    public var color: Int?
    public var user: String?
    public var deleted: Bool?
    public var lastUpdate: Int64?
    public var created: Int64?

    public init(_id: String?, name: String?, _description: String?, image: String?, color: Int?, user: String?, deleted: Bool?, lastUpdate: Int64?, created: Int64?) {
        self._id = _id
        self.name = name
        self._description = _description
        self.image = image
        self.color = color
        self.user = user
        self.deleted = deleted
        self.lastUpdate = lastUpdate
        self.created = created
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case _description = "description"
        case image
        case color
        case user
        case deleted
        case lastUpdate
        case created
    }

}

