//
// TeamMemberSyncDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TeamMemberSyncDto: Codable {

    public var _id: String?
    public var teamId: String?
    public var permission: Int?
    public var user: String?
    public var deleted: Bool?
    public var lastUpdate: Int64?
    public var created: Int64?

    public init(_id: String?, teamId: String?, permission: Int?, user: String?, deleted: Bool?, lastUpdate: Int64?, created: Int64?) {
        self._id = _id
        self.teamId = teamId
        self.permission = permission
        self.user = user
        self.deleted = deleted
        self.lastUpdate = lastUpdate
        self.created = created
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case teamId
        case permission
        case user
        case deleted
        case lastUpdate
        case created
    }

}

