//
// ToDoSyncDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ToDoSyncDto: Codable {

    public var _id: String?
    public var user: String?
    public var deleted: Bool?
    public var lastUpdate: Int64?
    public var created: Int64?
    public var projectId: String?
    public var name: String?
    public var _description: String?
    public var status: Int?
    public var dueDate: String?
    public var assignedUsers: String?
    public var estimatedHours: Int?
    public var estimatedMinutes: Int?

    public init(_id: String?, user: String?, deleted: Bool?, lastUpdate: Int64?, created: Int64?, projectId: String?, name: String?, _description: String?, status: Int?, dueDate: String?, assignedUsers: String?, estimatedHours: Int?, estimatedMinutes: Int?) {
        self._id = _id
        self.user = user
        self.deleted = deleted
        self.lastUpdate = lastUpdate
        self.created = created
        self.projectId = projectId
        self.name = name
        self._description = _description
        self.status = status
        self.dueDate = dueDate
        self.assignedUsers = assignedUsers
        self.estimatedHours = estimatedHours
        self.estimatedMinutes = estimatedMinutes
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case user
        case deleted
        case lastUpdate
        case created
        case projectId
        case name
        case _description = "description"
        case status
        case dueDate
        case assignedUsers
        case estimatedHours
        case estimatedMinutes
    }

}

