//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class VerifyPurchaseRequest: APIModel {

    public var isTest: Bool?

    public var orderId: String?

    public var packageName: String?

    public var productId: String?

    public var purchaseToken: String?

    public var test: Bool?

    public var userId: String?

    public init(isTest: Bool? = nil, orderId: String? = nil, packageName: String? = nil, productId: String? = nil, purchaseToken: String? = nil, test: Bool? = nil, userId: String? = nil) {
        self.isTest = isTest
        self.orderId = orderId
        self.packageName = packageName
        self.productId = productId
        self.purchaseToken = purchaseToken
        self.test = test
        self.userId = userId
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        isTest = try container.decodeIfPresent("isTest")
        orderId = try container.decodeIfPresent("orderId")
        packageName = try container.decodeIfPresent("packageName")
        productId = try container.decodeIfPresent("productId")
        purchaseToken = try container.decodeIfPresent("purchaseToken")
        test = try container.decodeIfPresent("test")
        userId = try container.decodeIfPresent("userId")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(isTest, forKey: "isTest")
        try container.encodeIfPresent(orderId, forKey: "orderId")
        try container.encodeIfPresent(packageName, forKey: "packageName")
        try container.encodeIfPresent(productId, forKey: "productId")
        try container.encodeIfPresent(purchaseToken, forKey: "purchaseToken")
        try container.encodeIfPresent(test, forKey: "test")
        try container.encodeIfPresent(userId, forKey: "userId")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? VerifyPurchaseRequest else { return false }
      guard self.isTest == object.isTest else { return false }
      guard self.orderId == object.orderId else { return false }
      guard self.packageName == object.packageName else { return false }
      guard self.productId == object.productId else { return false }
      guard self.purchaseToken == object.purchaseToken else { return false }
      guard self.test == object.test else { return false }
      guard self.userId == object.userId else { return false }
      return true
    }

    public static func == (lhs: VerifyPurchaseRequest, rhs: VerifyPurchaseRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
