//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class VerificationResponse: APIModel {

    public var message: String?

    public var orderId: String?

    public var productId: String?

    public var valid: Bool?

    public init(message: String? = nil, orderId: String? = nil, productId: String? = nil, valid: Bool? = nil) {
        self.message = message
        self.orderId = orderId
        self.productId = productId
        self.valid = valid
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        message = try container.decodeIfPresent("message")
        orderId = try container.decodeIfPresent("orderId")
        productId = try container.decodeIfPresent("productId")
        valid = try container.decodeIfPresent("valid")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(message, forKey: "message")
        try container.encodeIfPresent(orderId, forKey: "orderId")
        try container.encodeIfPresent(productId, forKey: "productId")
        try container.encodeIfPresent(valid, forKey: "valid")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? VerificationResponse else { return false }
      guard self.message == object.message else { return false }
      guard self.orderId == object.orderId else { return false }
      guard self.productId == object.productId else { return false }
      guard self.valid == object.valid else { return false }
      return true
    }

    public static func == (lhs: VerificationResponse, rhs: VerificationResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
