//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension TimesheetSyncApi.Synchronisation {

    /**
    Get projects

    Get dirty projects from server.
    */
    public enum GetProjectSyncData {

        public static let service = APIService<Response>(id: "getProjectSyncData", tag: "Synchronisation", method: "GET", path: "/v1/sync/getProjectSyncData", hasBody: false, securityRequirement: SecurityRequirement(type: "bearerAuth", scopes: []))

        public final class Request: APIRequest<Response> {

            public struct Options {

                public var syncState: Int

                public var limit: Int

                public var offset: Int

                public init(syncState: Int, limit: Int, offset: Int) {
                    self.syncState = syncState
                    self.limit = limit
                    self.offset = offset
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: GetProjectSyncData.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(syncState: Int, limit: Int, offset: Int) {
                let options = Options(syncState: syncState, limit: limit, offset: offset)
                self.init(options: options)
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                params["syncState"] = options.syncState
                params["limit"] = options.limit
                params["offset"] = options.offset
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = SyncData

            /** SyncData of the User */
            case status200(SyncData)

            /** Not authorized */
            case status401

            public var success: SyncData? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                default: return ()
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status401: return 401
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .status401: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(SyncData.self, from: data))
                case 401: self = .status401
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
