//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** timesheet.io provides a REST API that can be accessed directly from another web application or from within a Javascript single page application. The API can be used from any programming language.
This API should be used if you want to synchronise data between your client and the server.
Please email support@timesheet.io if you have questions or need help while using the API. */
public struct TimesheetSyncApi {

    /// Whether to discard any errors when decoding optional properties
    public static var safeOptionalDecoding = false

    /// Whether to remove invalid elements instead of throwing when decoding arrays
    public static var safeArrayDecoding = false

    /// Used to encode Dates when uses as string params
    public static var dateEncodingFormatter = DateFormatter(formatString: "yyyy-MM-dd'T'HH:mm:ssZZZZZ")

    public static let version = "1.0"

    public enum Billing {}
    public enum Device {}
    public enum Profile {}
    public enum Settings {}
    public enum Synchronisation {}

    public enum Server {

        /** Production Server **/
        public static let main = "https://sync.timesheet.io"
    }
}
