//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** The Timesheet Sync API is specifically designed for bi-directional synchronization between mobile clients (iOS/Android) and the Timesheet server.
## Key Features
- **Efficient Data Synchronization**: Optimized for bandwidth and battery usage
- **Conflict Resolution**: Smart handling of concurrent modifications
- **Offline Support**: Queue changes when offline for later synchronization
- **Delta Updates**: Transfer only changed data to minimize bandwidth
## Sync Protocol
The Sync API uses a timestamp-based synchronization protocol:
1. Client sends last sync timestamp
2. Server returns all changes since that timestamp
3. Client sends local changes
4. Server resolves conflicts and confirms changes
## Data Types
The following data types are synchronized:
- Time entries
- Projects
- Clients
- Tasks
- User settings
## Authentication
All API requests require authentication using either:
- **OAuth2 Bearer Token**: For user-authorized applications
- **API Key**: For server-to-server integrations
## Device Registration
New devices must be registered before synchronization can begin.
 */
public struct TimesheetSyncApi {

    /// Whether to discard any errors when decoding optional properties
    public static var safeOptionalDecoding = false

    /// Whether to remove invalid elements instead of throwing when decoding arrays
    public static var safeArrayDecoding = false

    /// Used to encode Dates when uses as string params
    public static var dateEncodingFormatter = DateFormatter(formatString: "yyyy-MM-dd'T'HH:mm:ssZZZZZ")

    public static let version = "1.0.0"

    public enum AppleStoreBilling {}
    public enum Billing {}
    public enum Device {}
    public enum GooglePlayBilling {}
    public enum Profile {}
    public enum Settings {}
    public enum Synchronisation {}

    public enum Server {

        /** Production Server **/
        public static let main = "https://sync.timesheet.io"
    }
}
