//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension TimesheetSyncApi.Settings {

    /**
    Get settings

    Get settings of current user.
    */
    public enum Get1 {

        public static let service = APIService<Response>(id: "get_1", tag: "Settings", method: "GET", path: "/v1/settings", hasBody: false, securityRequirement: SecurityRequirement(type: "bearerAuth", scopes: []))

        public final class Request: APIRequest<Response> {

            public init() {
                super.init(service: Get1.service)
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = SettingsDto

            /** Settings of the User */
            case status200(SettingsDto)

            /** Not authorized */
            case status401

            public var success: SettingsDto? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                default: return ()
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status401: return 401
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .status401: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(SettingsDto.self, from: data))
                case 401: self = .status401
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
