//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension TimesheetSyncApi.Profile {

    /**
    Get current user profile

    Retrieves the profile information of the authenticated user. This is typically called upon login to get user details and subscription status.
    */
    public enum Get {

        public static let service = APIService<Response>(id: "get", tag: "Profile", method: "GET", path: "/v1/profiles/me", hasBody: false, securityRequirement: SecurityRequirement(type: "bearerAuth", scopes: []))

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** The referrer URL where the user came from, used for analytics */
                public var referrer: String?

                /** Controls whether to include newsletter subscription status in the response or update subscription preference */
                public var newsletter: Bool?

                public init(referrer: String? = nil, newsletter: Bool? = nil) {
                    self.referrer = referrer
                    self.newsletter = newsletter
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: Get.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(referrer: String? = nil, newsletter: Bool? = nil) {
                let options = Options(referrer: referrer, newsletter: newsletter)
                self.init(options: options)
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let referrer = options.referrer {
                  params["referrer"] = referrer
                }
                if let newsletter = options.newsletter {
                  params["newsletter"] = newsletter
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = PublicProfileDto

            /** Profile retrieved successfully */
            case status200(PublicProfileDto)

            /** User is not authorized to access this endpoint */
            case status401

            /** Internal server error */
            case status500

            public var success: PublicProfileDto? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                default: return ()
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status401: return 401
                case .status500: return 500
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .status401: return false
                case .status500: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(PublicProfileDto.self, from: data))
                case 401: self = .status401
                case 500: self = .status500
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
