//
// ProfileAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ProfileAPI {
    /**
     Get profile

     - parameter referrer: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func callGet(referrer: String? = nil, completion: @escaping ((_ data: PublicProfileDto?,_ error: Error?) -> Void)) {
        callGetWithRequestBuilder(referrer: referrer).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get profile
     - GET /v1/profiles/me

     - examples: [{contentType=application/json, example={
  "country" : "country",
  "newsletter" : true,
  "language" : "language",
  "invoicePayment" : true,
  "trial" : true,
  "createdAt" : "2000-01-23T04:56:07.000+00:00",
  "euCustomer" : true,
  "inactive" : true,
  "stripePayment" : true,
  "members" : 5,
  "state" : "state",
  "subscriptionActive" : true,
  "plan" : 5,
  "zip" : "zip",
  "gdprConsent" : true,
  "licenseQuantity" : 7,
  "initials" : "initials",
  "includeTaxForBusiness" : true,
  "invited" : true,
  "subscriptionInactive" : true,
  "active" : true,
  "pro" : true,
  "plus" : true,
  "lastname" : "lastname",
  "validAndActivated" : true,
  "eu" : true,
  "at" : true,
  "taxId" : "taxId",
  "lastUpdate" : 2,
  "monthly" : true,
  "countryName" : "countryName",
  "activationDate" : "2000-01-23T04:56:07.000+00:00",
  "yearly" : true,
  "status" : 1,
  "expires" : 0,
  "firstname" : "firstname",
  "payPalPayment" : true,
  "city" : "city",
  "displayName" : "displayName",
  "startedTestimonial" : "2000-01-23T04:56:07.000+00:00",
  "pending" : true,
  "admin" : true,
  "valid" : true,
  "expired" : true,
  "licenseHolder" : true,
  "street" : "street",
  "imageUrl" : "imageUrl",
  "paymentOption" : "paymentOption",
  "member" : true,
  "currency" : "currency",
  "subscriptionCancelled" : true,
  "email" : "email",
  "validProfile" : true,
  "cancellationDate" : "2000-01-23T04:56:07.000+00:00",
  "product" : "product",
  "business" : "business",
  "permission" : 6,
  "referrer" : "referrer",
  "businessCustomer" : true,
  "cancellationOffer" : true,
  "user" : "user",
  "activatedTeams" : true,
  "activated" : true
}}]
     - parameter referrer: (query)  (optional)

     - returns: RequestBuilder<PublicProfileDto> 
     */
    open class func callGetWithRequestBuilder(referrer: String? = nil) -> RequestBuilder<PublicProfileDto> {
        let path = "/v1/profiles/me"
        let URLString = TimesheetSyncAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "referrer": referrer
        ])


        let requestBuilder: RequestBuilder<PublicProfileDto>.Type = TimesheetSyncAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
