//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension TimesheetSyncApi.GooglePlayBilling {

    /**
    Acknowledge Google Play subscription

    Acknowledge a Google Play subscription purchase to complete the transaction and prevent automatic refunds.
    */
    public enum AcknowledgeGooglePlaySubscription {

        public static let service = APIService<Response>(id: "acknowledgeGooglePlaySubscription", tag: "Google Play Billing", method: "POST", path: "/v1/billing/googleplay/subscription/acknowledge", hasBody: true, securityRequirement: SecurityRequirement(type: "bearerAuth", scopes: []))

        public final class Request: APIRequest<Response> {

            public var body: AcknowledgeRequest?

            public init(body: AcknowledgeRequest?, encoder: RequestEncoder? = nil) {
                self.body = body
                super.init(service: AcknowledgeGooglePlaySubscription.service) { defaultEncoder in
                    return try (encoder ?? defaultEncoder).encode(body)
                }
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = AcknowledgeResponse

            /** Acknowledgment successful */
            case status200(AcknowledgeResponse)

            /** Invalid subscription data or missing required parameters */
            case status400

            /** User not authorized or not registered */
            case status401

            public var success: AcknowledgeResponse? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                default: return ()
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status400: return 400
                case .status401: return 401
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .status400: return false
                case .status401: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(AcknowledgeResponse.self, from: data))
                case 400: self = .status400
                case 401: self = .status401
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
